### ISSUE TITLE
Updating Readme to make it more informative

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#1]
## README.md is very vague and doesn't clearly imply:

1. How the code works?
2. The general workflow

It can be made more informative and easier to read to help newcomers to understand it better.

**Comment by arnav1776** [comment]
I would like to work on this issue, quick query should I make pr after Hacktober fest starts or before?

**Comment by Kushalrock** [comment]
Sure why not. I am assigning the task to you.
If you want your PR to be counted for hacktoberfest. You should make the PR after hacktoberfest starts. I would recommend that you fork the repository now, do the required changes and then make a PR on October 1 that will be much more effective.

**Comment by arnav1776** [comment]
Ok thanks, will do.

**Comment by Kushalrock** [comment]
@arnav1776 Please take these two images and write in the readme about the old look and new look of the app.
![oldlook](https://user-images.githubusercontent.com/64556649/135504604-965402bf-eeda-4dca-8425-1f23b7d3f130.png)
![Screenshot_1633023644](https://user-images.githubusercontent.com/64556649/135504611-8c42a154-80ac-4aed-bc41-5e64d899c690.png)

The first one is the old look and the second one is the fresh look and give all the credit to @AyoubBoulahtar who helped us revamp our look.

P.S. trim the edges of the images do not include the buttons from the screenshot.

**Comment by arnav1776** [comment]
@Kushalrock please check out the readme that I had created till now based on the old looks https://github.com/arnav1776/routinger/blob/readme/README.md   & do you want me to update it with new images or should I add both the looks in it, also suggest any changes you'd like me to work on.

**Comment by Kushalrock** [comment]
It looks good. I am recommending a few changes like removing the sponsor project screen. In the add task screen select the scheduled task and click a photo of it and use it.

Regarding where to implement new looks use the pictures of new look in readme(replace the old look images) and yes take one of the pictures of old look and write in readme that we have changed our app looks.

Also please update the dependencies. Yesterday, after three merges we are using more dependencies.

[Optional] We want people to know how the project works. So if you have like a better idea. Like if we see the readme now it just shows the folder structure and dependencies. Something else which could make it informative like including that this file contains these functions and so on. Please also include that. 

**If you're planning on including this do so in a separate commit. So that you can revert back. **

**Comment by arnav1776** [comment]
Okay and can you please mail me all the screenshots to be included on arnav1776@gmail.com because my emulator is not running properly  so I am having some trouble running it.

**Comment by Kushalrock** [comment]
Yeah sure I will do that in a few hours @arnav1776

**Comment by arnav1776** [comment]
@Kushalrock I have updated everything except the images part please check it.

**Comment by Kushalrock** [comment]
It looks really good. Just update the images. For now, remove the dark mode and yes wherever you are adding the add task screen don't use the to-do drop down instead use the scheduled task to help people notice the vast array of options available to them.

@arnav1776

**Comment by arnav1776** [comment]
I had asked you to send me the images as my emulator wasn't working properly😅, that's why I had to leave the images part also please send the scheduled task which you have mentioned.

**Comment by Kushalrock** [comment]
Oh I am really sorry. I forgot, I will send you those in like 8-10 hours. Really sorry...

**Comment by Kushalrock** [comment]
Here are the images
![Screenshot_1633023644](https://user-images.githubusercontent.com/64556649/135703987-132db01d-92dd-4fd2-967b-b0a1cfa98425.png)
![Screenshot_1633150130](https://user-images.githubusercontent.com/64556649/135703988-26b8b03f-6887-4ef9-8ca0-22e2a05c1610.png)
![Screenshot_1633150137](https://user-images.githubusercontent.com/64556649/135703989-f04a8474-49a6-4891-9088-a8b5d7a3fae9.png)
![Screenshot_1633150143](https://user-images.githubusercontent.com/64556649/135703990-a4191d25-11ee-4bfe-b929-b5af8b90c0f4.png)
![Screenshot_1633150149](https://user-images.githubusercontent.com/64556649/135703991-6c21300f-fd1b-4922-bff7-c09498b2755c.png)
![Screenshot_1633150161](https://user-images.githubusercontent.com/64556649/135703993-9f36942f-a14d-4c39-8912-ffc90c7aa226.png)
![Screenshot_1633150189](https://user-images.githubusercontent.com/64556649/135703995-4e58789d-c2f8-4e3c-91ae-32a20de744c1.png)

**Comment by Kushalrock** [comment]
@arnav1776 Please check the images

**Comment by Kushalrock** [comment]
I have also sent you the images in your email from helproutinger@gmail.com

**Comment by arnav1776** [comment]
Thank you for sending, I will update it and open a pr.

**Comment by Kushalrock** [comment]
Sure. No need for thanks. In fact, I should thank you, your help and contribution are more than appreciated.

**Comment by Kushalrock** [comment]
@arnav1776  You did a great job. I just saw your Word press portfolio too it was awesome.

We are looking forward to creating a website for routinger with react. Would you like to join hands with us??

**Comment by arnav1776** [comment]
Sure I would love to work on the project but I only know the basics of react as I had only recently started learning it.

**Comment by Kushalrock** [comment]
If you have any other suggestions. We are all ears.
