### ISSUE TITLE
A new icon for the Routinger app

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#2]
Visual aspects of an app are as important as the coding aspect. 

The primary identity of an app is its icon. We are inviting people to make a new icon for the app. The same icon will be used as the primary app icon, the first image that is shown when the app loads & the same icon will be used in the notification service. 

**If you have ideas about using over one image in different areas. We duly invite it.**

## Where to place the icons?
We must respect contribution guidelines and Code of conduct at every point. 

You can place your icons in `dev_assets` and issue a pull request. The new icon must be named accordingly and must not replace the original files. It should be named as `new_splash_icon`. If you have made an adaptive icon along with the original one. It should be named as `new_splash_icon_adaptive`.
![Capture](https://user-images.githubusercontent.com/64556649/134764543-a178d6cf-63c5-4d33-a109-84705f9bc406.PNG)

**Comment by AyoubBoulahtar** [comment]
Can you assign me ? I wanna suggest some ideas.

**Comment by Kushalrock** [comment]
Yeah why not. The more the merrier🙂🙂
