### ISSUE TITLE
Shifting from hardcore values to variables

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#25]
**Is your feature request related to a problem? Please describe.**
The app uses hard-coded values for border radius, which are tried and tested, but it is bound to change in the future. It will be very hectic to go to each file and change it. Instead, we can make a field in config file and import that field and use it.

**Describe the solution you'd like**
Going to config file, and creating well-named variables for hardcoded values and importing the same in the places of use.

**Additional context**
This will help fellow coders understand the code much easier, also it will make changes easier.

**Comment by GrbavaCigla** [comment]
Assign me :D
