### ISSUE TITLE
Add Alert Dialog Box

### ISSUE THREAD

**Issue by Perumallpardhiv** [Routinger/routinger#29]
After adding tasks to It, If the user press the delete symbol by mistake then It will be deleted, 
This can be solved easily by adding a Alert dialog box to it

@Kushalrock 
@AyoubBoulahtar 
Pls check my issue and, If the issue I described is true, then Assign this to me

If possible add hacktoberfest-accepted label to this issue

**Comment by Kushalrock** [comment]
@Perumallpardhiv Would you like to implement the issue? I can raise a issue and add you to it.

**Comment by Perumallpardhiv** [comment]
@Kushalrock 
Pls assign that to me

**Comment by Kushalrock** [comment]
@Perumallpardhiv Once you are done with the issue and open a PR I will add the hacktoberfest-accepted label.

**Comment by Perumallpardhiv** [comment]
@Kushalrock pls check my pr #30
