### ISSUE TITLE
A new color palette or font-style for the app

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#3]
Color palettes and fonts can completely revamp user experiences. Changing these two things can have a revolutionary impact.

The present color palette is very dull and potentially unwelcoming. If you have a better idea about a color palette we are very excited to hear about it. 

## How to suggest a color palette and/or font?

After forking the repo. You can navigate to `dev_assets` and create a new small text file `color_palette_font_recommendation.txt`. In this simple text file, you can write about the color_palette you are thinking about using. If the same file exists, we recommend not overwrite it but add a number after the file name.  

If you have made a mockup of the app with your color palette/ and or font in some software you can post that too with the same name and in any `popular image formats`.
![Capture](https://user-images.githubusercontent.com/64556649/134765312-5580b41b-f51d-4c4d-877b-a6bc21184933.PNG)

**Comment by AyoubBoulahtar** [comment]
Can you assign me to this one too ?
I'll send a screenshot with a correspondent color palette and font.

**Comment by Kushalrock** [comment]
Instead of a screenshot. You can just follow the instructions mentioned. Or write about what you're going to use here in the comments. 🙂

I can surely assign it to you.

**Comment by AyoubBoulahtar** [comment]
Sure, thanks.

**Comment by Kushalrock** [comment]
The issue is successfully resolved.
