### ISSUE TITLE
Several print statements in the console and usage of unnecessary null checks

### ISSUE THREAD

**Issue by AyoubBoulahtar** [Routinger/routinger#6]
**Describe the bug**
The app logs a lot of unneeded debugging statements.
Also the usage of null checks is unnecessary and not good for readability.

<img width="385" alt="null checks" src="https://user-images.githubusercontent.com/49714931/134824339-76bbc9d9-3365-4555-97e1-bc55078c92f2.png">

**Expected behavior**
Slight improvements could do for this stuff.

**Comment by Kushalrock** [comment]
Yes that's true. The null checks could be improved. The print statements were made to facilitate debugging but they were not removed and this is cluttering the debug console. 

Thank you for pointing out the issue 

If you're up for it. I can assign you the task.

**Comment by AyoubBoulahtar** [comment]
I could make the adjustments, you can assign it to me.

**Comment by Kushalrock** [comment]
Okay I am assigning the task to you. But yes take care not to break anything because I know for a fact that null check is actually required if a person exit the calendar or time chooser without selecting anything. So we can use the ?. operator instead of null check.

**Comment by AyoubBoulahtar** [comment]
I cleaned the project from all obvious unnecessary print statements, although this List is not used in the app at all.

What's your opinion about that ?

<img width="461" alt="print" src="https://user-images.githubusercontent.com/49714931/134976909-34ecc090-1f32-4fed-b301-a1e045c5ddaf.png">
<img width="464" alt="cache" src="https://user-images.githubusercontent.com/49714931/134976917-ae149e6c-31af-4472-94c6-55d6c1b6ea7a.png">

**Comment by AyoubBoulahtar** [comment]
For the null checks, I think if we did a validator instead of checking if the value was null, it would work great, a user can't create scheduled task without specifiying Date and Time for it.

**Comment by Kushalrock** [comment]
Yes pending notification list is not used for the time being you can comment it out. 

Without specifying date and time user cannot create scheduled task but they can exit out if the calendar and time picker by tapping else where in the screen in that case the date picker and time picker returns null.

**Comment by AyoubBoulahtar** [comment]
Yes they can exit the calendar and time picker, but they can not create a task without those specified, isn't that the expected behavior?
