### ISSUE TITLE
Weekly Chart Showing Number Of Tasks Completed

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#7]
**Is your feature request related to a problem? Please describe.**
A chart where I can see my weekly stats below the experience points card. Such as how many tasks have I completed and so on.

**Describe the solution you'd like**
A line chart starting at Monday ending with Sunday showing how many tasks (Scheduled+Recurring) completed on a given day of the week.

**Describe alternatives you've considered**
Instead of merging both the scheduled and recurring there can be separate line charts for both of them.

**Additional context**
--None--

**Comment by bayush-9** [comment]
Hi @Kushalrock , I would like to work on it!

**Comment by Kushalrock** [comment]
I am currently working on it. However, I can need help to debug later. I will create an issue and assign it to you. Sorry for the confusion.
