### ISSUE TITLE
BUG: RendexBox overflowing in home page

### ISSUE THREAD

**Issue by AyoubBoulahtar** [Routinger/routinger#8]
**Describe the bug**
RendexBox overflowing in tasks expansion panel in home page

**To Reproduce**
Add a scheduled task

**Expected behavior**
Text needs to wrap to next line when reaching its container constraintes

**Ways to solve it**
wrap in wrap widget

**Comment by Kushalrock** [comment]
Check it if it has been resolved with the latest commit. If yes, then I will close the issue.

**Comment by Kushalrock** [comment]
With the latest commit, it has been refactored a bit more. Now it wraps properly around text.
