### ISSUE TITLE
Fixing Imports to make the code more readable

### ISSUE THREAD

**Issue by Kushalrock** [Routinger/routinger#9]
The imports were organized by keeping in mind a specific style. But with the addition of new packages and imports, the imports have gone messy. We encourage beginners to take up this issue and fix the imports across all the files.

A simple example is
![Capture](https://user-images.githubusercontent.com/64556649/135236709-957697cf-ff63-4637-8366-001b3272df04.PNG)
![Capture2](https://user-images.githubusercontent.com/64556649/135236718-c17f5cf6-372f-4123-a4ae-ae4d6d0bc850.PNG)

The first image is of unorganized imports while the second image is of organized imports.
The general structure to be followed is
- Dart Imports(Look for dart:__ to know what to include here)
- Flutter Package Imports (Look for package:flutter to know what to include here)
- Third-Party Packages (All the packages aside from dart and flutter should be in this category)
- Then folder wise imports of local files

Imports should have a parent category like in the image, dart imports, helper imports, and so on..

The files having package:routinger are local files and should be accessed by relative location using ./ or ../ instead of using the package:routinger.

**Comment by Kushalrock** [comment]
Change all the files to follow this structure of imports.

Thank you for your contribution in advance.

**Comment by bayush-9** [comment]
Hi @Kushalrock  I would like to work on it!

**Comment by Kushalrock** [comment]
Hello there, Sure I will assign it to you right away. Follow the structure that is followed in the above images. 

Thank you again

**Comment by bayush-9** [comment]
Yeah sure, I'll keep them in mind.

**Comment by Kushagrasaxena-13** [comment]
I want to work on this can you assign it to me

**Comment by Kushalrock** [comment]
@Kushagrasaxena-13  It's already assigned to someone. However there are more easy issues coming in. You can contribute to them instead.

**Comment by Kushalrock** [comment]
@bayush-9  Make sure that your commit contains all the files and should be even with the main branch at the time of making PR. Because we are trying to be very active and new code files are being added every day. So yeah, fetch the upstream every time.

Hope your experience with our project goes well.

**Comment by bayush-9** [comment]
Sure @Kushalrock

**Comment by Rishavgupta12345** [comment]
can i work on this ?

**Comment by Kushalrock** [comment]
The issue is closed and needs no further changes.
